### ISSUE TITLE
Tilt sensor

### ISSUE THREAD

**Issue by ddimakis42** [jannopet/LEGO-WeDo-2.0-Python-SDK#2]
Hello,
congratulations on your project, it's amazing!
I am not sure if you are still following this repository. If you still are,I have a problem with the get_tilt() function 
Sometimes (i am not sure why) the function crashes and i get the following message

Traceback (most recent call last):
  File "wedo_tilt.py", line 12, in <module>
    a = hub1.get_tilt()
  File "/home/teacher/.local/lib/python3.6/site-packages/wedo2/smarthub.py", line 228, in get_tilt
    angle = tilt_sensor.get_angle()
  File "/home/teacher/.local/lib/python3.6/site-packages/wedo2/services/tilt_sensor.py", line 81, in get_angle
    if len(data_set_numbers) == 2:
TypeError: object of type 'NoneType' has no len()

this is in a while that constantly checks the tilt value
Am I doing something wrong? Is there a way to avoid the crash?

**Comment by ddimakis42** [comment]
If anyone is interested there is a simple solution

in tilt_sensor.py 
you have to check 
if data_set_numbers is not None:
before
 if len(data_set_numbers) == 2:
                return self.tilt_sensor_angle_make(data_set_numbers[0], data_set_numbers[1])
that way if the sensor does not send a number (probably some problem with bled) the program does not crash and you get a zero value.
If you want to detect the zero values to ignore them, you can check if they are integer (get_tilt returns a tuple of floats)
I'm writing this a little hastily, so if someone wants a more elaborate explanation, leave a comment
